[package]
name = "aranet_archiver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.77"
btleplug = "0.11.3"
futures = "0.3.30"
futures-util = "0.3.30"
tokio = { version = "1.35.1", features = [ "time", "rt-multi-thread", "macros" ] }
uuid = "1.6.1"
