[package]
name = "aranet_archiver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
btleplug = "0.10.4"
futures = "0.3.26"
futures-util = "0.3.26"
tokio = { version = "1.26.0", features = [ "time", "rt-multi-thread", "macros" ] }
uuid = "1.3.0"
